# Generated by Django 3.0 on 2022-09-09 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageto', models.CharField(default='', max_length=1000)),
                ('message', models.CharField(default='', max_length=1000)),
                ('messagefrom', models.CharField(default='', max_length=1000)),
                ('currentdate', models.CharField(default='', max_length=1000)),
                ('filename', models.ImageField(upload_to='media')),
                ('suspicious', models.CharField(default='0', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailid1', models.CharField(default='', max_length=100)),
                ('name1', models.CharField(default='', max_length=100)),
                ('gender1', models.CharField(default='', max_length=100)),
                ('country1', models.CharField(default='', max_length=100)),
                ('profession1', models.CharField(default='', max_length=100)),
                ('mobilenumber1', models.CharField(default='', max_length=100)),
                ('emailid2', models.CharField(default='', max_length=100)),
                ('name2', models.CharField(default='', max_length=100)),
                ('gender2', models.CharField(default='', max_length=100)),
                ('country2', models.CharField(default='', max_length=100)),
                ('profession2', models.CharField(default='', max_length=100)),
                ('mobilenumber2', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UploadFileData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filetype', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('file', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='userdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobilenumber', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=50)),
                ('softdelete', models.CharField(default='0', max_length=50)),
            ],
        ),
    ]
