from django.db import models
class userdata(models.Model):
	name=models.CharField(max_length=50)
	mobilenumber=models.CharField(max_length=50)
	email=models.CharField(max_length=100)
	password=models.CharField(max_length=30)
	gender=models.CharField(max_length=50)
	country=models.CharField(max_length=50)
	profession=models.CharField(max_length=50)
	softdelete=models.CharField(max_length=50,default="0")
class UploadFileData(models.Model):
	filetype=models.CharField(max_length=50)
	name=models.CharField(max_length=50)
	file=models.CharField(max_length=50) 
class FriendRequest(models.Model):
	emailid1=models.CharField(max_length=100,default="")
	name1=models.CharField(max_length=100,default="")
	gender1=models.CharField(max_length=100,default="")
	country1=models.CharField(max_length=100,default="")
	profession1=models.CharField(max_length=100,default="")
	mobilenumber1=models.CharField(max_length=100,default="")
	emailid2=models.CharField(max_length=100,default="")
	name2=models.CharField(max_length=100,default="")
	gender2=models.CharField(max_length=100,default="")
	country2=models.CharField(max_length=100,default="")
	profession2=models.CharField(max_length=100,default="")
	mobilenumber2=models.CharField(max_length=100,default="")
	status=models.CharField(max_length=100,default="")
class ChatDetails(models.Model):
	messageto=models.CharField(max_length=1000,default="")
	message=models.CharField(max_length=1000,default="")
	messagefrom=models.CharField(max_length=1000,default="")
	currentdate=models.CharField(max_length=1000,default="")
	filename=models.ImageField(upload_to="media")
	suspicious=models.CharField(max_length=10,default="0")